### ISSUE TITLE
Warnings in all_sha1s when repository contains garbage

### ISSUE THREAD

**Issue by book** [frioux/Cogit#9]
Here's a simple one-liner that I just run in one of my repositories:

    $ perl -MCogit -le 'print for Cogit->new(directory=>".")->all_sha1s->all' >/dev/null
    Use of uninitialized value $1 in concatenation (.) or string at /home/book/perl5/lib/perl5/Cogit/Loose.pm line 53.
    Use of uninitialized value $2 in concatenation (.) or string at /home/book/perl5/lib/perl5/Cogit/Loose.pm line 53.

After inspecting the code in `all_sha1s`, and the content of my `.git` directory, this showed up:

    $ find .git | grep /[a-f0-9][a-z0-9]/ | grep -vE /.{38}
    .git/objects/b1/tmp_obj_vsFrDb

So the code's assumption that all files matching `m{[/\\][a-z0-9]{2}[/\\]}` also match `m{([a-z0-9]{2})[/\\]([a-z0-9]{38})}` is incorrect.

After some searching, I found another way to have Git tell me about those files:

    $ git count-objects -v >/dev/null
    warning: garbage found: .git/objects/b1/tmp_obj_vsFrDb

I assume this is some temporary file left over after a Git crash or `^C` at the wrong time.

The file went away after I ran `git prune`. [This page](http://gitolite.com/tips-3.html#garbage-collection) has a few more Git garbage collection tricks.

**Comment by frioux** [comment]
You think the warning should match git's or just not return that file or
what?

--

**Comment by book** [comment]
I didn't think about throwing a better warning, but matching what Git does sounds like a good idea.

On the other hand, I could find only one very specific Git command (and option, see below) that outputs this warning:

    $ git count-objects -v >/dev/null
    warning: garbage found: .git/objects/b1/tmp_obj_vsFrDb

Other commands I expected to peek at `.git/objects/` were quiet about garbage files:

    $ git count-objects >/dev/null
    $ git cat-file --batch-check --batch-all-objects >/dev/null
    $ git rev-list --all --objects >/dev/null
    $ git fsck >/dev/null
    Checking object directories: 100% (256/256), done.
    Checking objects: 100% (2169/2169), done.
    $ git repack >/dev/null
    Counting objects: 4, done.
    Delta compression using up to 4 threads.
    Compressing objects: 100% (4/4), done.
    Writing objects: 100% (4/4), done.
    Total 4 (delta 0), reused 0 (delta 0)

In fact, after checking the source, it turns out that `git count-object` is the *only* command to output this warning:

    $ ack --no-color --no-heading --cc "garbage found"
    builtin/count-objects.c:25:		return "garbage found";

And it does this only with the `-v` option enabled:

    static void loose_garbage(const char *path)
    {
        if (verbose)
            report_garbage(PACKDIR_FILE_GARBAGE, path);
    }

So, after giving it too much thought, I'd just skip unexpected files, and be quiet about them, just like Git is in most cases.

**Comment by frioux** [comment]
Fixed with merge of #10
